#!/bin/bash
cd $(cd `dirname $0` && pwd)

# Only default script
script="main.php"

phpbin=(
    "/usr/local/php/bin/php"
    "/usr/local/bin/php52"
    "/usr/local/bin/php55"
)
for bin in ${phpbin[@]}; do
    echo -e "\e[1;33m`$bin -v | head -n1`\e[0m"
    $bin $script "$@"
done
